### ISSUE TITLE
Create a script to send all givbacks as a batch in one tx

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/givback-calculation#10]
related to https://github.com/Giveth/giv-token-contracts/pull/51#issuecomment-1055387470

Now https://givback.develop.giveth.io/api-docs/#/default/get_calculate_givback generate function for aragon to vote, but due we have limit of transaction size we have to split it to some batch that every batch contains 200 addresses,  so if in a round we have lots of addresses it would make it hard ( because we need maybe over 20 transactions and one voting per transaction and it's huge), so we are searching for a way to send givbacks in just on tx
 The result of the session that I and @divine-comedian  and @paxthemax had, is:
 - [ ] I need to hash data and hash to response [How to hash](https://github.com/Giveth/giv-token-contracts/blob/2aa5b17455e29de3fd430fc1a97d22e2f268d00d/test/GivBacksRelayer/GIVBacksRelayer.test.ts#L34-L42)
 - [ ] For hash I need to get nonce from calling a smart contract (@divine-comedian  can you give me the smart contract that I should call?)
 - [ ] I should change `"connect 0xA1514067E6fE7919FB239aF5259FfF120902b4f9 token-manager 
voting:1 act agent:0 0x18a46865AAbAf416a970eaA8625CFC430D2364A1 sendGIVbacks(address[],uint256[]) 
[0xad9c46a9ab1a96ef80001cc5c153cc4b58232da3,0x826976d7c600d45fb8287ca1d7c76fc8eb732030,0x4ff14c2f19cf78
ffd249b22d622e6ee7e25b84d8,0xec952ed8e7c2aa466cac36fd611d2e87df1243d7,0xb7562f12e41c762cecda99d62bd6ea
c7b0c3b4c1,0x1a7e76c3bc4006e804842c232d91767d3c5299d2,0x77c3db040f79ae46a91529a667c03ab484b37116,0xe
4f0e8ae1fd76928a6f586a2ec6a120ccdc50a8e,0x8afc051de5f3941a68d3dbb9c7c96ec773ef494b,0x05903affd45da43a14
f9a9421605e0e7a4fe2e21,0x7c5361f5bb5e2bb123c95e69bed331f3b0b8f094,0x29cf75f4622dbedbc63354e28f6e734635
690f4b,0x66339e64c3447f32251a3baf79bc7f4192fd1386,0x05a1ff0a32bc24265bcb39499d0c5d9a6cb2011c,0x243f5dea
d21bd50bad298e0efd5ed0e957e8bf0a,0x2473fb8eebe46041d5f528a728505c26a81c1158] 
[1352270000000000000000,264279999999999970000,53760000000000000000,37410000000000000000,213800000
00000000000,13350000000000000000,8020000000000000000,4810000000000000000,3750000000000000000,338
0000000000000000,2610000000000000000,2250000000000000000,830000000000000000,750000000000000000,5
30000000000000000,310000000000000000]"` to something else, but currently don't know what

**Comment by divine-comedian** [comment]
You'll run GIVbacks calculations as normal - GIVprice, GIVfactor, USD value of donations etc.. then the response output will need to change. 

We'll keep the first action `connect 0xA1514067E6fE7919FB239aF5259FfF120902b4f9 token-manager voting:1`

then we'll use the agent to send action (`act`) to the relayer contract - the funcion is `addBatches` or something like this 

then we will have an array of each batch, this will replace having a separate response for each `smartContractcall` - this might look something like 

```
connect 0xA1514067E6fE7919FB239aF5259FfF120902b4f9 token-manager voting:1
act agent:0 {relayerAddress} addBatches(bytes32[] calldata batches) [batch1hashData] [batch2hashData] [batch3hashData] 
```

the `nonce()` you can get from calling a function on the relayer contract which will return to you the current nonce - I believe we want to use the current nonce +1 i.e if nonce returns 3 then we send 4(3+1) as nonce data for each batch of hashData. i.e 
i.e current nonce is 3
batch1hashData nonce = 4
batch2hashData nonce = 5
batch3hashData nonce = 6

I can't seem to find the first deployment of the relayer contract but I'm sure @paxthemax  knows where to find it.

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
Can we close this issue?

**Comment by divine-comedian** [comment]
YES!
