### ISSUE TITLE
Convert project to typescript to make it easy to share knowledge with other contributors

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/givback-calculation#13]
Now I'm the only one who knows whats happening in this script, and because this was supposed to be a simple project but step by step we implemented features in unplanned times the codes became messy and it's very hard to involve other contributors, I suggest convert project to typescript and after defining input/output for functions and do some refactoration I can involve @CarlosQ96  in this project

**Comment by mohammadranjbarz** [comment]
@divine-comedian 

I had implemented this along time ago, I would appreciate if you can test
https://givback.develop.giveth.io/staging/api-docs/

And compare it with 

https://givback.develop.giveth.io/api-docs/

to see wether it works fine or not

**Comment by divine-comedian** [comment]
@mohammadranjbarz 
not a good start for 

![image](https://user-images.githubusercontent.com/67759413/198312592-4aa97614-7de4-48b0-8f90-fa7e0580e3ad.png)

https://givback.develop.giveth.io/staging/api-docs/

**Comment by divine-comedian** [comment]
Okay I am testing all of the APIs to compare that they work and give the same results in the json output - I am comparing them in VScode using `diff`

# calculate
parameters:
![image](https://user-images.githubusercontent.com/67759413/198370980-151a596a-8bf6-4e99-a6ee-4922dc645a4e.png)
differences:
#### looks like in staging in "niceEarned" if the value is not 0 it is wrapped in quotations - also the decimal precision is limited to two places 
![image](https://user-images.githubusercontent.com/67759413/198371143-20727dfc-ca63-46bd-be66-5c2f04dff70e.png)

#### also it appears two addresses show up in staging that do not show up in production
`0xf632ce27ea72dea30d30c1a9700b6b3bceaa05cf`
`0x41cb654d1f47913acab158a8199191d160dabe4a`
![image](https://user-images.githubusercontent.com/67759413/198371246-595a31c1-6aee-4210-8822-674d7402de12.png)

# eligible-donations
parameters are same dates as above in calculate

no diff :heavy_check_mark: 

# not-eligible-donations
parameters same as above

no diff :heavy_check_mark: 

# purplelist donations
same parameters as above
no diff :heavy_check_mark: 

# donations leaderboard
parameters:
![image](https://user-images.githubusercontent.com/67759413/198372220-d8b82ad7-853a-4582-9eb1-763410d99317.png)

seems like they are calculating different amounts - even though there is no other differences in the file 
![image](https://user-images.githubusercontent.com/67759413/198373805-2b791b2d-1a77-4205-aa22-b2be31324b77.png)

# giv price

no diff :heavy_check_mark: 

# purplelist 

staging is showing two extra addresses - correlating to the same ones we saw in `calculate` API 
![image](https://user-images.githubusercontent.com/67759413/198374242-3889517a-23d6-47c6-a526-41bcd5dd17ed.png)

# nice-token donations
parameters:
![image](https://user-images.githubusercontent.com/67759413/198374479-db6fbd5c-165f-402c-82c6-1f158afa010c.png)

looks like a similar issue in staging where if the value of niceTokens isn't 0 they are wrapped in quotation marks and the decimal precision is limited to two decimal places. 

also on staging it is missing these transactions (both from sem)
- `0xa64e7bbf8f98ead79c5f51cedbbffe8bb8f8f04fcc48ca91168a5ecab7bc465d`
- `0xcafb63fd38433fad6104ff6b408346ce6d86b6b2c3159a3ef2ff2325aeb141e5`

**Comment by mohammadranjbarz** [comment]
@divine-comedian  Thanks for you tests, the `.env` file was different was different in two ENVs I copied the on that was in production for stagin, now the purple list is the same

**Comment by mohammadranjbarz** [comment]
It has been implemented long time ago
