### ISSUE TITLE
Change givback calculation output for supporting batches

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/givback-calculation#14]
> @divine-comedian  requested:
next step is to modify our regular GIVbacks setup to begin using the relayer contract. We'll need to make some modifications to this API: https://givback.develop.giveth.io/api-docs/#/default/get_calculate_givback  So that it matches the output of this one: https://givback.develop.giveth.io/api-docs/#/default/get_calculate_givback_retroactive  So this means - converting GIVbacks data into batch hashes, modify the output script to include the relayer, the batches data and the ipfs link

**Comment by divine-comedian** [comment]
This has been up and working for several rounds, Ashley has been using it without issue, moving to DONE!
