### ISSUE TITLE
setup API for NICE token calculations 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/givback-calculation#18]
from my discussion w/ @mohammadranjbarz 
<blockquote>
The purpose of this API is to collect donations of certain whitelisted tokens to a certain project on giveth in a given time period and tell us the total sum of token donations for each individual donor to the whitelisted project  and tell us how many NICE tokens we should mint for each donor

it will accept these parameters:

- start date 
- end date
- whitelisted tokens
- projectId
- NICE minting ratio

and it will return 2 CSV files 

the <b>1st</b> with just data needed for distribution: 
distribution:
- donor address
- NICE tokens to receive
- token Symbol (NICE)

the <b>2nd</b> with more complete donation data for review/analysis:
- donor address
- eligible donation date
- eligible donation currency
- eligible donation amount
- projectId
- NICE tokens earned for donation
</blockquote>

**Comment by MoeNick** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/givback-calculation/18?planning-poker) with ZenHub @mohammadranjbarz

**Comment by divine-comedian** [comment]
tested this out and checked the nice eligible donations against the regular givbacks eligible donations, looks to be capturing all the right data! 
you can see some of the work I did comparing results here:
https://docs.google.com/spreadsheets/d/1JHdNW45KNf5h1mcf4ZiIMqe-vkl6Q_RwtC0KnT1IStU/edit?usp=sharing

the csv file outputs are working well too! Calling this done!
