### ISSUE TITLE
combine givback and nice calculation data

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/givback-calculation#21]
nice token and givback rewards are calculated on the same two week schedule.

since anyone who donates to giveth will get givbacks, since it is a verified project this means that anyone who is eligible for $nice tokens is also getting GIVbacks. It will become simpler for us to manage and communicate data by combining this data into one endpoint. 

so we use calculate-givback as the base, then we add the other checks in the calculate-nice API to determine if they receive nice tokens and how much.

- we check if that user made donations to the whitelisted projects, in any of the whitelisted tokens
- we calculate the amount of nice they should receive based on the value of their donation and the nicePerDollar. 
- append this information in another column on the givbackreport csv as "niceEarned"

I'm open to other ideas of implementation. the main goal is that we want to run 1 API to know how much rewards, both GIVbacks and $nice to send out at the end of each round

**Comment by mohammadranjbarz** [comment]
I deleted `/calculate-givbacks` and `/calculate-nice-token` and now we just have `/calculate` , it's deployed on staging, if you say it's ok we can deploy it on production
https://givback.develop.giveth.io/staging/api-docs/#/default/get_calculate, please check the output with production output to make sure it's ok

**PS** I added a **niceEarned** column to CSV

**Comment by mohammadranjbarz** [comment]
> I deleted `/calculate-givbacks` and `/calculate-nice-token` and now we just have `/calculate` , it's deployed on staging, if you say it's ok we can deploy it on production https://givback.develop.giveth.io/staging/api-docs/#/default/get_calculate, please check the output with production output to make sure it's ok
> 
> **PS** I added a **niceEarned** column to CSV

@divine-comedian

**Comment by divine-comedian** [comment]
just a few comments @mohammadranjbarz 

since we have two things happening can you make the input parameter names more clear 

whitelistTokens -> niceWhitelistTokens
projectSlugs -> niceProjectSlugs
relayerAddress -> givRelayerAddress

also this was probably an oversight on my part but purple list addresses should be able to donate and receive nice tokens
as well.

**Comment by mohammadranjbarz** [comment]
@divine-comedian Nice catch, thanks for your feedback, I made changes and it's deployed on staging

**Comment by divine-comedian** [comment]
> @divine-comedian Nice catch, thanks for your feedback, I made changes and it's deployed on staging

changes look good. I asked @WhyldWanderer to review since she will be using this more often than anyone.
you can check it out here - https://givback.develop.giveth.io/staging/api-docs/#/default/get_calculate

**Comment by divine-comedian** [comment]
> hey, why i'm getting $nice only but no $GIV?

If you have any support requests can you reach out on our discrod?

https://discord.giveth.io
