### ISSUE TITLE
Running calculate with different relayerAddress returns nonce of -1

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/givback-calculation#35]
Currently running https://givback.develop.giveth.io/api-docs/#/default/get_calculate

I ran it with some data and the output gave a nonce of -1, the nonce should always start at 0 and go up by 1 per batch 

I made a short video to show the parameters and the output together:
https://github.com/Giveth/givback-calculation/assets/67759413/9ff9a469-2cb3-413d-9890-d664941fd4fa

I also tested this using different months and GIV prices and it gave me the same result

EDIT: 
The error looks to be related to changing the relayer address from the default one 

When I enter the address for the relayer on optimism the nonce responds with -1 
ref: `0xf13e93af5e706ab3073e393e77bb2d7ce7bec01f`

**Comment by mohammadranjbarz** [comment]
@divine-comedian  I pushed something, now the negative nonce problem has been fixed, and also I return different nonce for `Optimism` and `Other chains`, so you can test for instance with your wallet address you will see that OP nonce is much smaller than other chain because your nonce in gnosis is bigger, please test it and tell me if you had more feedbacks

**Comment by divine-comedian** [comment]
This looks fine but small issue, since we have merged the responses together we should hardcode the relayerAddresses into the responses, since we don't split up the responses by chain anymore 

- [ ] allOtherChains should be: `0xd0e81E3EE863318D0121501ff48C6C3e3Fd6cbc7`
- [ ] Optimism should be: `0xf13e93af5e706ab3073e393e77bb2d7ce7bec01f`

**Comment by mohammadranjbarz** [comment]
@divine-comedian 

Done

<img width="1187" alt="Screen Shot 1402-06-22 at 10 15 20" src="https://github.com/Giveth/givback-calculation/assets/9850545/3d6dcbf0-d737-4c60-9621-2713a483241b">
<img width="1200" alt="Screen Shot 1402-06-22 at 10 15 36" src="https://github.com/Giveth/givback-calculation/assets/9850545/7ca0fd71-5ec8-4afa-885b-c6d086be2d80">

**Comment by divine-comedian** [comment]
Great! Calling this DONE
