### ISSUE TITLE
calculate API returns less responses for bigger date range?? 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/givback-calculation#37]
Testing on: https://givback.develop.giveth.io/api-docs/#/default/get_calculate

I ran calculate on `allOtherChains` for these dates:
- `2023/05/14-16:00:00` to  `2023/08/14-16:00:00`
- Returned 450 rows

ran calculate on `allOtherChains` for these dates:
- `2023/06/14` to `2023/08/14`
- returned 488 rows

![image](https://github.com/Giveth/givback-calculation/assets/67759413/b271490a-fb92-4d9f-9c6d-5e6eca8decb1)

Left side is first query, right side is second query

---

### Am I crazy?? 
Shouldn't the query that has the widest date range return more entries? Why is there less rows returned for a query over 1 month more time? 

Here's the files:
[givbackReport_allOtherChains_2023_05_14-16_00_00-2023_08_14-16_00_00.csv](https://github.com/Giveth/givback-calculation/files/12588853/givbackReport_allOtherChains_2023_05_14-16_00_00-2023_08_14-16_00_00.csv)
[givbackReport_allOtherChains_2023_06_14-16_00_00-2023_08_14-16_00_00.csv](https://github.com/Giveth/givback-calculation/files/12588854/givbackReport_allOtherChains_2023_06_14-16_00_00-2023_08_14-16_00_00.csv)

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
I investigated what you said and found the reason, 

In the code I ignore the givbacks for those that their share is less than `0.000001` , and when you use bigger range some wallet addresses share will decrease to less than that amount so we ignore them, and this is the reason those list become smaller some times.

https://github.com/Giveth/givback-calculation/blob/staging/src/utils.ts#L36C1-L42C5

**Comment by divine-comedian** [comment]
Oh okay, we can call this a negligible loss then, thanks for checking it out
