### ISSUE TITLE
Staging isn't working

### ISSUE THREAD

**Issue by kkatusic** [Giveth/givback-calculation#62]
Staging not working: https://givback.develop.giveth.io/staging/api-docs

**Comment by mohammadranjbarz** [comment]
@kkatusic This is the staging address
https://givback.develop.giveth.io/api-docs/

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz you should than change it or remove it inside _[README.md](https://github.com/Giveth/givback-calculation/blob/staging/README.md)_ file :)

Thanks man, done

**Comment by kkatusic** [comment]
Thx @mohammadranjbarz
